### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [HexCodeFFF/pyralkit#1]
Heya, does this have any documentation or?

**Comment by machineonamission** [comment]
Uhhh kinda

I was trying to auto generate docs and the code for that should still be present *somewhere*

**Comment by machineonamission** [comment]
Seems you need Sphinx in the docs folder

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Ah alright, thanks! Maybe this should also be automated for the readthedocs site? :P

**Comment by machineonamission** [comment]
I was trying to get that working but I gave up a while ago lmao

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Ah understandable, i had the same pain for my own thing lol, maybe a GitHub Wiki could be done instead? Shouldn't be too hard to be done
