### ISSUE TITLE
Save system as Python files

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [HexCodeFFF/pyralkit#2]
Heya, is it possible to save my system as a python file(s)? :P

Planning on using this to represent our sys in code form that we could easily import into pk and edit it there, since it'd be easier to clean up from there imo

**Comment by machineonamission** [comment]
Currently there is no built in way to do that but it should be easy to loop
over all properties of the system you want, shove them in a  dict, snd save
it as a json

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Ah fair enough, thanks aha

Is there a way to grab all members? Looked through the code but couldn't find it myself

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Oops

**Comment by machineonamission** [comment]
> Is there a way to grab all members? Looked through the code but couldn't find it myself

https://github.com/HexCodeFFF/pyralkit/blob/b8c1047c2c4b37e6d647abe376d89a3794804e8e/pyralkit/client.py#L299-L311

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
How did i miss that lmao, thanks!

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Sorry to reopen this lol but my code won't actually... Run? I've called the get_system_members function but gotten nothing, this is my code
```python
import asyncio
import pyralkit

pk = pyralkit.PKClient("my token here")

async def main():
    m = await pk.get_system_members()
    for i in m:
        print(m, flush=True)

    await pk.close()

loop = asyncio.new_event_loop()
a = asyncio.run_coroutine_threadsafe(main(), loop)
a.result()```
